CM6: Fix audio parameter parser AIDL dependency
FAILED: analyzing Android.bp files and generating ninja file at
out/soong/build.lineage_CM6.ninja
Outputs: out/soong/build.lineage_CM6.ninja
Error: exited with code: 1
Command: cd "$(dirname "out/host/linux-x86/bin/soong_build")" &&
BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd /
&& env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"
--out "out"     --soong_variables out/soong/soong.lineage_CM6.variables
-o out/soong/build.lineage_CM6.ninja --kati_suffix -lineage_CM6
--kati_enabled -l out/.module_paths/Android.bp.list --available_env
out/soong/soong.environment.available --used_env
out/soong/soong.environment.used.lineage_CM6.build Android.bp
Output:
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": depends on multiple versions of the
same aidl_interface: android.hardware.audio.core-V3-ndk-source,
android.hardware.audio.core-V4-ndk-source
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:reuse objects}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static}
           via tag cc.dependencyTag: { name:gen source}
    -> android.hardware.audio.core-V3-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:reuse objects}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static}
           via tag cc.dependencyTag: { name:gen header export}
    -> android.hardware.audio.core-V3-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:gen source}
    -> android.hardware.audio.core-V3-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V3-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:gen header export}
    -> android.hardware.audio.core-V3-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared,cfi:cfi}
           via tag cc.dependencyTag: { name:reuse objects}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static,cfi:cfi}
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:true explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:reuse objects}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static}
           via tag cc.dependencyTag: { name:gen source}
    -> android.hardware.audio.core-V4-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared,cfi:cfi}
           via tag cc.dependencyTag: { name:reuse objects}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static,cfi:cfi}
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:true explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:reuse objects}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static}
           via tag cc.dependencyTag: { name:gen header export}
    -> android.hardware.audio.core-V4-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared,cfi:cfi}
           via tag cc.dependencyTag: { name:reuse objects}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static,cfi:cfi}
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:true explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:gen source}
    -> android.hardware.audio.core-V4-ndk-source{}
[31merror:[0m vendor/transsion/CM6/Android.bp:70589:1: module
"android.hardware.audio.parameter_parser.service" variant
"android_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:false explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared,cfi:cfi}
           via tag cc.dependencyTag: { name:reuse objects}
->
av-audio-types-aidl-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:static,cfi:cfi}
via tag cc.libraryDependencyTag: {
Kind:sharedLibraryDependency Order:normalLibraryDependency
wholeStatic:false reexportFlags:true explicitlyVersioned:false
explicitlyImpl:false dataLib:false ndk:false staticUnwinder:false
makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false
excludeInNonApex:false unexportedSymbols:false}
->
android.hardware.audio.core-V4-ndk{os:android,arch:arm64_armv8-2a-dotprod,link:shared}
           via tag cc.dependencyTag: { name:gen header export}
    -> android.hardware.audio.core-V4-ndk-source{}