CM6: Drop ClearKey CAS plugin
The plugin introduces a dependency on
libprotobuf-cpp-full-21.12-vendorcompat, which triggers
16 KiB page-size ELF alignment checks during the build.

[ 93% 16799/17931 30m56s remaining]
//prebuilts/misc/protobuf_vendorcompat:libprotobuf-cpp-full-21.12-vendorcompat
check elf file
FAILED:
out/soong/.intermediates/prebuilts/misc/protobuf_vendorcompat/libprotobuf-cpp-full-21.12-vendorcompat/android_vendor_arm64_armv8-2a-dotprod_shared/libprotobuf-cpp-full-21.12.so.check_elf_file
out/host/linux-x86/bin/check_elf_file --skip-unknown-elf-machine
--max-page-size 16384 --soname libprotobuf-cpp-full-21.12.so
--shared-lib
out/soong/.intermediates/bionic/libc/libc/android_vendor_arm64_armv8-2a-dotprod_shared/libc.so
--sh
ared-lib
out/soong/.intermediates/system/logging/liblog/liblog/android_vendor_arm64_armv8-2a-dotprod_shared/liblog.so
--shared-lib
out/soong/.intermediates/bionic/libm/libm/android_vendor_arm64_armv8-2a-dotprod_shared/libm.so
--shared-lib
out/soong/.intermediates/external/zlib/libz/android_vendor_arm64_armv8-2a-dotprod_shared/libz.so
--shared-lib
out/soong/.intermediates/prebuilts/clang/host/linux-x86/libc++/android_vendor_arm64_armv8-2a-dotprod_shared/libc++.so
--shared-
lib
out/soong/.intermediates/bionic/libdl/libdl/android_vendor_arm64_armv8-2a-dotprod_shared/libdl.so
--system-shared-lib libdl.so
--llvm-readobj=prebuilts/clang/host/linux-x86/clang-r563880c/bin/llvm-readobj
prebuilts/misc/protobuf_vendo
rcompat/arm64/libprotobuf-cpp-full-21.12.so && touch
out/soong/.intermediates/prebuilts/misc/protobuf_vendorcompat/libprotobuf-cpp-full-21.12-vendorcompat/android_vendor_arm64_armv8-2a-dotprod_shared/libprotobuf-cpp-full-21.12.so.check_el
f_file
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
error: Load segment has alignment 4096 but 16384 required.
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note: Fix suggestions:
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:   use linker flag "-Wl,-z,max-page-size=16384" when compiling this
lib
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note: If the fix above doesn't work, bypass this check with:
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:   Android.bp: ignore_max_page_size: true,
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:   Android.mk: LOCAL_IGNORE_MAX_PAGE_SIZE := true
prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so:
note:   Device mk: PRODUCT_CHECK_PREBUILT_MAX_PAGE_SIZE := false
01:46:54 ninja failed with: exit status 1
There were 3 actions that completed after the action that failed. See
verbose.log.gz for their output.

#### failed to build some targets (12:54 (mm:ss)) ####