CM6: Destroy Transsion services stack
ERROR: files are incompatible: The following instances are in the device
manifest but not specified in framework compatibility matrix:
    vendor.anc.fingerprint.extension.IFingerprintExtension/default (@1)
    vendor.dolby.dms.IDms/default (@1)
    vendor.hardware.trancharge.ITranCharge/default (@1)
    vendor.hardware.tranled.ITranLed/default (@1)
    vendor.hardware.trantp.ITrantp/default (@1)
    vendor.transsion.hardware.aegis.IAegisService/default (@1)
    vendor.transsion.hardware.screeninfo.IScreenInfo/default (@1)
vendor.transsion.hardware.security.deviceauthen.IDeviceAuthen/default
(@1)
    vendor.transsion.hardware.security.hap.IHap/default (@1)
vendor.transsion.hardware.security.paytrigger.IPayTrigger/default
(@1)
vendor.transsion.hardware.security.rpmbservice.IRpmbservice/default
(@1)
vendor.transsion.hardware.security.trancriticalparavfy.ITranCriticalParaVfy/default
(@1)
    vendor.transsion.hardware.tne.tneengine.ITne/default (@1)
vendor.transsion.hardware.trancam.trancamserver.ITrancamserver/default
(@1)
    vendor.transsion.hardware.tranfacaidl.ITranfacAidl/default (@1)
    vendor.transsion.hardware.trannet.ITranNet/default (@5)
    vendor.transsion.hardware.tranradio.ITranRadio/default (@11)
vendor.transsion.hardware.transtorage.storage.IAidlStorage/default
(@1)
    vendor.transsion.performance.sched.ITransSched/default (@2)
    vendor.transsion.tranHwInfo.ITranHwInfo/default (@1)
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility
matrices with FCM version >= 202504.
3. For new platform HALs, add them to any framework compatibility matrix
with FCM version >= 202504 where applicable.
4. For device-specific HALs, add to
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or
DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.
5. For `android.*` HALs that are using unexpected instance names, the
instance names need to be added to the AOSP framework compatibility
matrices. A regex wildcard can be used if the instance names are
proprietary.